In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]

In [6]:
one_hot_repr

[[9217, 2199, 5998, 5929],
 [9217, 2199, 5998, 3840],
 [9217, 5170, 5998, 3960],
 [5035, 4996, 3009, 7543, 641],
 [5035, 4996, 3009, 7543, 7393],
 [1601, 9217, 2113, 5998, 7099],
 [2896, 6981, 6774, 7543]]

In [7]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9217 2199 5998 5929]
 [   0    0    0    0 9217 2199 5998 3840]
 [   0    0    0    0 9217 5170 5998 3960]
 [   0    0    0 5035 4996 3009 7543  641]
 [   0    0    0 5035 4996 3009 7543 7393]
 [   0    0    0 1601 9217 2113 5998 7099]
 [   0    0    0    0 2896 6981 6774 7543]]


In [11]:
## feature representation
dim = 10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 292ms/step


array([[[-0.02447101, -0.02591641,  0.02710355, -0.00851079,
         -0.03500209, -0.03465373,  0.02448601,  0.04314791,
         -0.0392747 , -0.02677164],
        [-0.02447101, -0.02591641,  0.02710355, -0.00851079,
         -0.03500209, -0.03465373,  0.02448601,  0.04314791,
         -0.0392747 , -0.02677164],
        [-0.02447101, -0.02591641,  0.02710355, -0.00851079,
         -0.03500209, -0.03465373,  0.02448601,  0.04314791,
         -0.0392747 , -0.02677164],
        [-0.02447101, -0.02591641,  0.02710355, -0.00851079,
         -0.03500209, -0.03465373,  0.02448601,  0.04314791,
         -0.0392747 , -0.02677164],
        [ 0.00622699,  0.01746491, -0.01060738,  0.0248622 ,
         -0.00610012, -0.04971414, -0.00935582, -0.04827736,
          0.04356475, -0.04612586],
        [-0.01951882,  0.04919193, -0.02837346, -0.02081442,
         -0.02261128, -0.02742907, -0.00531241, -0.03080642,
         -0.01365522,  0.00947871],
        [ 0.03873806, -0.02069248, -0.01346137,  0.0